# csv logger built in lightning
# original refer to: https://github.com/ashleve/lightning-hydra-template/blob/main/configs/logger/csv.yaml

csv:
  _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
  save_dir: "${paths.output_dir}"
  name: "csv/"
  prefix: ""
