# https://neptune.ai
# original refer to: https://github.com/ashleve/lightning-hydra-template/blob/main/configs/logger/neptune.yaml
# modify refer to: https://github.com/nathanpainchaud/lightning-hydra-template/blob/main/src/lightning_hydra_template/configs/logger/neptune.yaml
# modify project 

neptune:
  _target_: lightning.pytorch.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  # project: username/lightning-hydra-template
  project: username/${call:os.path.basename,${oc.env:PROJECT_ROOT}}
  # name: ""
  log_model_checkpoints: True
  prefix: ""
